name: CI

on: push

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Proof HTML
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: docs/
  lint-css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint CSS
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          stylelint_input: '**/*.css'
